apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailywellness-API
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dailywellness-app
  template:
    metadata:
      labels:
        app: dailywellness-app
    spec:
      containers:
      - name: dailywellness-container
        image: adesokanayo/dailywellness:1.0.0
        volumeMounts:
          - name: storage
            mountPath: temp/keys/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
        - name: storage
          emptyDir: {}
        