name: Test
on: [push, pull_request]
env:
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  HTTP_PORT: 8004
  GRPC_PORT: 9004
  GRPC_HEALTH_PORT: 10004

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.0
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run --config=.golangci_lint.yaml
  test:
    needs: lint
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          go build
          go test -v ./... -coverprofile=coverage.txt -cover

      - name: Create Env File and Load Secret
        run: |
          touch .dailywellness.env
          echo ${{ secrets.DAILYWELLNESS_ENV }} >> .dailywellness.env 

      - name: List Directory
        run: |
          ls
          cat .dailywellness.env